### ISSUE TITLE
Re-Fold & Re-Trig not appearing in collection despite being added from library

### ISSUE THREAD

**Issue by alefnull** [wiqid/repelzen#24]
as the title states, i've added all modules and even subscribed to the plugin itself in the VCV library, but these two modules refuse to appear in my local library.

**Comment by Petervos2018** [comment]
Ok try this :

Go here https://library.vcvrack.com/plugins?query=repel&license=&sort=buildTimestamp

Choose Remove all, and also remove the Repelzen folder from your hdd.
Start Rack,
Close rack

In the Library choose "Subscribe" for the repelzen.

Start Rack the library should have a red dot, update repelzen.

Restart rack, and they should all be there.

**Comment by alefnull** [comment]
this indeed solved the issue, thanks a bunch!

i'm guessing it had something to do with the fact that i had built the plugin from source before it was re-added to the library, so i was still 'using' an outdated build. just a guess.
