### ISSUE TITLE
repelzen-1.1.0_beta2_pre0706-lin does not show up in module browser

### ISSUE THREAD

**Issue by ContemporaryInsanity** [wiqid/repelzen#4]
Unpacked & copied to .Rack/plugins-v1 as usual, modules do not show up in module browser.  Linux Mint 19.1.

**Comment by wiqid** [comment]
you shouldn't need to unpack it. just drop it in the plugins-v1 directory, and rack will unpack it. either way, it should work. is there anything about repelzen in your log file?

**Comment by ContemporaryInsanity** [comment]
[0.123 warn src/plugin.cpp:161] Could not load plugin /home/ewen/.Rack/plugins-v1/repelzen: Failed to load library /home/ewen/.Rack/plugins-v1/repelzen/plugin.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/ewen/.Rack/plugins-v1/repelzen/plugin.so)

**Comment by wiqid** [comment]
i take it you have a different glibc version? you may need to compile this yourself, or wait for the plugin library team to do it when we get to the regular release

**Comment by ContemporaryInsanity** [comment]
I guess so, all other modules work fine though.  I can wait.  Thanks for
your work, much appreciated.

**Comment by wiqid** [comment]
@ContemporaryInsanity does the linux version of the new beta2 work for you? it was compiled on ubuntu 16.04.

**Comment by ContemporaryInsanity** [comment]
Just done a quick test, all seems fine now, thank you.  From a first glance I particularly like the re-burst module.
